tests(*): scope assert handles to subtests
These changes move Testify `assert` handles from "parent" tests into
subtests so Testify's error messages can refer to a particular test case
in a table of tests vs. the whole table which is more ambiguous.

Previously, if a test case fails:

    % go test ./cmd/cli -run TestIsMonitoredNamespace
    --- FAIL: TestIsMonitoredNamespace (0.00s)
        metrics_test.go:264:
                    Error Trace:    metrics_test.go:264
                    Error:          Not equal:
                                    expected: false
                                    actual  : true
                    Test:           TestIsMonitoredNamespace
    FAIL
    FAIL    github.com/openservicemesh/osm/cmd/cli  0.419s
    FAIL

With these changes:

    % go test ./cmd/cli -run TestIsMonitoredNamespace
    --- FAIL: TestIsMonitoredNamespace (0.00s)
        --- FAIL: TestIsMonitoredNamespace/Testing_if_ns-2_exists_is_monitored (0.00s)
            metrics_test.go:264:
                    Error Trace:    metrics_test.go:264
                    Error:          Not equal:
                                    expected: false
                                    actual  : true
                    Test:           TestIsMonitoredNamespace/Testing_if_ns-2_exists_is_monitored
    FAIL
    FAIL    github.com/openservicemesh/osm/cmd/cli  0.396s
    FAIL

Signed-off-by: Jon Huhn <johuhn@microsoft.com>